---



stages:
    - Build
    - SAST Scan

Build:
    image: maven:3.8.1-jdk-11
    stage: Build
    script:
        - mvn -f app/pom.xml compile package
    artifacts:
        paths:
            - target/verademo.war

Pipeline-Scan:
  image: veracode/pipeline-scan:latest
  allow_failure: true
  stage: SAST Scan
  script:
    - java -jar /opt/veracode/pipeline-scan.jar 
        -vid $VERACODE_API_KEY_ID -vkey $VERACODE_API_KEY_SECRET 
        --file ./target/verademo.war

Policy-Scan:
    image: veracode/api-wrapper-java:latest
    stage: SAST Scan
    only:
        - schedules
        - master
    script:
        - java -jar /opt/veracode/api-wrapper.jar -vid ${TEAM_ANALYSISCENTER_ID} -vkey ${TEAM_ANALYSISCENTER_KEY}
          -action UploadAndScan -appname "Gitlab" -createprofile false -autoscan true
          -filepath ./target/verademo.war -version "Job ${CI_JOB_ID} in pipeline ${CI_PIPELINE_ID}"
          -scantimeout 15
